
<div  align="center" class="columnContainer clearFix"><span class="title">Agendamento de Consultas</span></div>
<div class="columnContainer clearFix">
    <div id="agbusca">
        <div id="select">
            <div class="dropdown">
                 <?php  echo $this->form->especialidades ?>  
            </div>
        </div>        
            <?php echo $this->form->button ?>        
    </div>                    
</div>
<div class="columnContainer clearFix">
    
<?php 
if(isset($this->dados)):   
    foreach ($this->dados as  $data => $id_horarios):
        foreach ($id_horarios as $id => $horarios):    
            $hrs = array_chunk( $horarios, ( round(count($horarios)/2)), true );
?>
    
        <div>
                <div class="content">                        
                    <div class="info_clinica">                           
                        <div id="nome" ><?php echo $id ?></div>                            
                        <div id="logo"><div>foto</div></div>
                        <div id="endereco"><!-- endereço --></div>                           
                    </div> 

                    <div class="grade">
                        <div class="data"> <?php echo $data ?>  </div>
                        <div class="horarios">

                         <!-- array left -->   
                        <?php
                        if(isset($hrs[0])):
                            foreach ($hrs[0] as $id_h => $h):
                        ?> 
                                <div class="column">
                                    <div class="radio"><input name="horario" id="<?php echo $id_h ?>" type="checkbox"></div><div><?php echo $h ?></div>
                                </div>
                        <?php                             
                            endforeach;
                        endif;    
                        ?>                                   

                         <!-- array right -->   
                        <?php
                        if(isset($hrs[1])):
                            foreach ($hrs[1] as $id_h => $h):
                        ?> 
                                <div class="column">
                                    <div class="radio"><input name="horario" id="<?php echo $id_h ?>" type="checkbox"></div><div><?php echo $h ?></div>
                                </div>
                        <?php                             
                            endforeach;
                        endif;
                        ?>                          
                         
                        </div>
                        <div class="line"></div>
                        <div class="bt-confirma">
                            <button type="button" id="button" name="bt">Confirmar</button>                
                        </div>
                    </div>                        


                </div>    
        </div>
    
<?php
        endforeach;
    endforeach;
endif;
?>        
</div>
