
<div  align="center" class="columnContainer clearFix"><span class="title">Agendamento de Consultas</span></div>
<div class="columnContainer clearFix">
    <div id="agbusca">
        <div id="select">
            <div class="dropdown">
                 <?php  echo $this->form->especialidades ?>  
            </div>
        </div>        
            <?php echo $this->form->button ?>        
    </div>                    
</div>
<div class="columnContainer clearFix">
    <div class="content">                        
        <div class="info_clinica">                           
            <div id="nome" >Clínicas Unidas - Dra. Laura Silveira</div>                            
            <div id="logo"><div>logo</div></div>
            <div id="endereco">Endereço: Rua Mostardeiro 945, Sala 102 Independência, Porto Alegre</div>                           
        </div> 

        <div class="grade">
            <div class="data">17/08/2014</div>
            <div class="horarios">

                <div class="column">
                    <div class="radio"><input type="radio" name="horario" ></div><div>9:00</div>
                    <div class="radio"><input type="radio" name="horario"  ></div><div>9:30</div>
                    <div class="radio"><input type="radio" name="horario"  ></div><div>10:00</div>
                    <div class="radio"><input type="radio" name="horario"  ></div><div>10:30</div>
                </div>

                <div class="column">
                    <div class="radio"><input type="radio" name="horario" ></div><div>13:00</div>
                    <div class="radio"><input type="radio" name="horario"  ></div><div>13:30</div>
                    <div class="radio"><input type="radio" name="horario"  ></div><div>14:00</div>
                    <div class="radio"><input type="radio" name="horario"  ></div><div>15:00</div>
                </div>

            </div>
            <div class="line"></div>
            <div>
                <button type="button" id="button" name="bt">Confirmar</button>                
            </div>
        </div>                        


    </div>                    
</div>
