

    <div class="columnContainer clearFix">
        
        <div id="quemsomos">
         
            <div id="info">
                <ul>
                    <li>Entre em contato conosco pelo telefone 51 3423-8911 ou por outros meios abaixo </li>
                    <li>E-mail: agendafacil@agendafacil.com.br </li>
                    <li>Endereço: Rua Jerônimo , 100 - Sala 10 . CEP: 90600-000  </li>
                    <li>Porto Alegre - Rio Grande do Sul</li>
                    
                </ul>  
            </div>
        </div>
    </div>

              

