

    <div class="columnContainer clearFix">
        <div id="banner"><img src="<?php echo $this->baseUrl('/images/banner.jpg') ?>" border="0"></div>
        <div id="leftContent">
            <div id="hbusca">
                <div id="select">
                    <?php  echo $this->form->especialidades ?>                    
                </div>
                    <?php echo $this->form->button ?>
            </div>
            <div id="info">
                <ul>
                    <li>Agenda Fácil é um portal que tem por objetivo aproximar médicos e pacientes.</li>
                    <li>Não precisa sair de casa para agendar uma consulta, nem aguardar em filas ou ficar esperando para falar com um atendente.</li>
                    <li>Acesso é rádipo e fácil disponivel 24 horas por dia.</li>
                    <li>Consulte uma especialidade e escolha qual melhor dia e horário.</li>
                    <li>São diversas especialidades e médicos, valores são reduzidos e você só paga pela consulta.</li>
                </ul>  
            </div>
        </div>
    </div>

    <div class="columnContainer clearFix">
        <div id="infoContainer" >
            <div id="info1">
                <p style="padding-top: 2px; text-indent: 60px;"> agendar uma consulta é </p>                                
                <p style="text-indent: 60px;"> simples e fácil</p>
                <p style="padding-top: 21px;text-indent:110px">1º escolha uma especialidade</p>
            </div>

            <div id="info2">
                <p style="padding-top: 2px; text-indent: 110px;">2º escolha o horário</p>
                <p style="text-indent: 110px;"> e o médico </p>
                <p style="padding-top: 21px;text-indent:60px">3º agende uma consulta</p>
            </div>

            <div id="info3">
                <p style="text-indent: 60px; padding-top: 11px;">4º efetue o pagamento</p>                            
                <p style="padding-top: 30px;text-indent:110px">5º aguarde a confirmação e pronto!</p>
            </div>
        </div>
    </div>                

