<div id="mainContent">

    <div class="columnContainer clearFix">
        <div id="banner"><img src="<?php echo $this->baseUrl('/images/banner.jpg') ?>" border="0"></div>
        <div id="leftContent">
            <div id="hbusca">
                <div id="select">
                    <div class="dropdown">
                        <select>
                            <option value="">Selecione uma especialidade...</option>
                            <option value="Alergia e Imunologia">Alergia e Imunologia</option>
                            <option value="Andrologia">Andrologia</option>
                            <option value="Anestesiologia">Anestesiologia</option>
                            <option value="Angiologia">Angiologia</option>                                        
                            <option value="Cancerologia">Cancerologia</option>                                        
                            <option value="Cardiologia">Cardiologia</option>                                        
                            <option value="Cirurgia  Aparelho Digestivo Alto">Cirurgia  Aparelho Digestivo Alto</option>
                            <option value="Cirurgia Aparelho Digestivo">Cirurgia Aparelho Digestivo</option>
                            <option value="Cirurgia Aparelho Digestivo Alto">Cirurgia Aparelho Digestivo Alto</option>
                            <option value="Cirurgia Aparelho Disgestivo">Cirurgia Aparelho Disgestivo</option>
                            <option value="Cirurgia Aparelho Disgestivo e Bariátrica">Cirurgia Aparelho Disgestivo e Bariátrica</option>
                            <option value="Cirurgia Aparelho Gastro Intestinal">Cirurgia Aparelho Gastro Intestinal</option>
                            <option value="Cirurgia Bariátrica">Cirurgia Bariátrica</option>
                            <option value="Cirurgia Buco Maxilo Facial">Cirurgia Buco Maxilo Facial</option>
                            <option value="Cirurgia Bucofacial">Cirurgia Bucofacial</option>
                            <option value="Cirurgia Cabeça e Pescoço">Cirurgia Cabeça e Pescoço</option>
                            <option value="Cirurgia Cardíaca">Cirurgia Cardíaca</option>
                            <option value="Cirurgia Cardiovascular">Cirurgia Cardiovascular</option>
                            <option value="Cirurgia Cardiovascular Pediátrica">Cirurgia Cardiovascular Pediátrica</option>
                            <option value="Cirurgia Cranio Maxilo">Cirurgia Cranio Maxilo</option>
                            <option value="Cirurgia Crânio Maxilo Facial">Cirurgia Crânio Maxilo Facial</option>
                            <option value="Cirurgia Craniomaxilofacial">Cirurgia Craniomaxilofacial</option>
                            <option value="Cirurgia da Coluna">Cirurgia da Coluna</option>
                            <option value="Cirurgia da Mão">Cirurgia da Mão</option>
                            <option value="Cirurgia Dentistária">Cirurgia Dentistária</option>
                            <option value="Cirurgia do Aparelho Digestivo">Cirurgia do Aparelho Digestivo</option>
                            <option value="Cirurgia do Aparelho Disgestivo">Cirurgia do Aparelho Disgestivo</option>
                            <option value="Cirurgia e Traumatologia Bucomaxilofacial">Cirurgia e Traumatologia Bucomaxilofacial</option>
                            <option value="Cirurgia Endovascular">Cirurgia Endovascular</option>
                            <option value="Cirurgia Figado Pâncreas e Vias Biliares">Cirurgia Figado Pâncreas e Vias Biliares</option>
                            <option value="Cirurgia Geral">Cirurgia Geral</option>
                            <option value="Cirurgia Geral Transplantes">Cirurgia Geral Transplantes</option>
                            <option value="Cirurgia Geral/Cirurgia Aparelho Digestivo">Cirurgia Geral/Cirurgia Aparelho Digestivo</option>
                            <option value="Cirurgia Ginecológica">Cirurgia Ginecológica</option>
                            <option value="Cirurgia Laparoscopia">Cirurgia Laparoscopia</option>
                            <option value="Cirurgia Oncológica">Cirurgia Oncológica</option>
                            <option value="Cirurgia Oncológica">Cirurgia Oncológica</option>
                            <option value="Cirurgia Oncologica e Geral">Cirurgia Oncologica e Geral</option>
                            <option value="Cirurgia Pediátrica">Cirurgia Pediátrica</option>
                            <option value="Cirurgia Plástica">Cirurgia Plástica</option>
                            <option value="Cirurgia Pré Transplantes">Cirurgia Pré Transplantes</option>
                            <option value="Cirurgia Torácica">Cirurgia Torácica</option>
                            <option value="Cirurgia Tumores Ósseos e Partes Moles">Cirurgia Tumores Ósseos e Partes Moles</option>
                            <option value="Cirurgia Vascular">Cirurgia Vascular</option>
                            <option value="Cirurgia Videolaparoscopia">Cirurgia Videolaparoscopia</option>
                            <option value="Citopatologia ">Citopatologia </option>
                            <option value="Clínica Cirúrgica">Clínica Cirúrgica</option>
                            <option value="Clínica Geral">Clínica Geral</option>
                            <option value="Clínica Médica">Clínica Médica</option>
                            <option value="Colo-Proctologia">Colo-Proctologia</option>
                            <option value="Colonoscopia">Colonoscopia</option>
                            <option value="Coloproctologia">Coloproctologia</option>
                            <option value="Coloproctologia Pediátrico">Coloproctologia Pediátrico</option>
                            <option value="Coluna Vertebral">Coluna Vertebral</option>
                            <option value="Craniomaxilo Facial">Craniomaxilo Facial</option>
                            <option value="Dentistica">Dentistica</option>
                            <option value="Dermatologia">Dermatologia</option>
                            <option value="Diagnóstico por  Imagem">Diagnóstico por  Imagem</option>
                            <option value="Disfunção da Articulação Temporomandibular (ATM) e Dor Orofacial ">Disfunção da Articulação Temporomandibular (ATM) e Dor Orofacial </option>
                            <option value="Doença Trofoblástica Gestacional">Doença Trofoblástica Gestacional</option>
                            <option value="Doenças Infecto Parasitárias">Doenças Infecto Parasitárias</option>
                            <option value="Doenças Sexualmente Transmissíveis">Doenças Sexualmente Transmissíveis</option>
                            <option value="Dor">Dor</option>
                            <option value="Dor Crônica">Dor Crônica</option>
                            <option value="Ecocardiografia">Ecocardiografia</option>
                            <option value="Ecoendoscopia">Ecoendoscopia</option>
                            <option value="Eletrofisiologia">Eletrofisiologia</option>
                            <option value="Eletrofisiologia - Cardiologia">Eletrofisiologia - Cardiologia</option>
                            <option value="Eletroneuromiografia">Eletroneuromiografia</option>
                            <option value="Endocrinilogia">Endocrinilogia</option>
                            <option value="Endocrinologia">Endocrinologia</option>
                            <option value="Endodontia">Endodontia</option>
                            <option value="Endoscopia">Endoscopia</option>
                            <option value="Endoscopia Digestiva">Endoscopia Digestiva</option>
                            <option value="Enfermagem">Enfermagem</option>
                            <option value="Estomatologia ">Estomatologia </option>
                            <option value="Fisioterapia">Fisioterapia</option>
                            <option value="Foniatria">Foniatria</option>
                            <option value="Fonoaudiologia">Fonoaudiologia</option>
                            <option value="Gastro adolescente">Gastro adolescente</option>
                            <option value="Gastroenterologia">Gastroenterologia</option>
                            <option value="Gastroenterologia Digestiva">Gastroenterologia Digestiva</option>
                            <option value="Gastroenterologia Pediátrica">Gastroenterologia Pediátrica</option>
                            <option value="Gastrologia">Gastrologia</option>
                            <option value="Gastrologia - Cirurgia Geral">Gastrologia - Cirurgia Geral</option>
                            <option value="Gastrologia - Hepatologia">Gastrologia - Hepatologia</option>
                            <option value="Gastrologia Pediátrica">Gastrologia Pediátrica</option>
                            <option value="Genética">Genética</option>
                            <option value="Geriatria">Geriatria</option>
                            <option value="Ginecologia">Ginecologia</option>
                            <option value="Ginecologia e Obstetrícia">Ginecologia e Obstetrícia</option>
                            <option value="Hematologia">Hematologia</option>
                            <option value="Hematologia e Hemoterapia">Hematologia e Hemoterapia</option>
                            <option value="Hematologia Pediátrica">Hematologia Pediátrica</option>
                            <option value="Hemodinâmica">Hemodinâmica</option>
                            <option value="Hepatologia">Hepatologia</option>
                            <option value="Hipertensão Pulmonar">Hipertensão Pulmonar</option>
                            <option value="Histeroscopia">Histeroscopia</option>
                            <option value="Implantodontia">Implantodontia</option>
                            <option value="Imunologia">Imunologia</option>
                            <option value="Infectologia">Infectologia</option>
                            <option value="Infectologia Pediátrica">Infectologia Pediátrica</option>
                            <option value="Infectologista">Infectologista</option>
                            <option value="Intensivismo">Intensivismo</option>
                            <option value="Intensivismo Pediátrico">Intensivismo Pediátrico</option>
                            <option value="Iodoterapia">Iodoterapia</option>
                            <option value="Mastologia">Mastologia</option>
                            <option value="Medicina de Viagem Infectologia">Medicina de Viagem Infectologia</option>
                            <option value="Medicina do Exercício e do Esporte">Medicina do Exercício e do Esporte</option>
                            <option value="Medicina do Trabalho">Medicina do Trabalho</option>
                            <option value="Medicina Fetal">Medicina Fetal</option>
                            <option value="Medicina Interna">Medicina Interna</option>
                            <option value="Medicina Nuclear">Medicina Nuclear</option>
                            <option value="Micro Cirurgia Reconstrutiva">Micro Cirurgia Reconstrutiva</option>
                            <option value="Microcirurgia">Microcirurgia</option>
                            <option value="Nefro-transplantes">Nefro-transplantes</option>
                            <option value="Nefrologia">Nefrologia</option>
                            <option value="Neonatologia">Neonatologia</option>
                            <option value="Neurocirurgia">Neurocirurgia</option>
                            <option value="Neuroendocrinologia">Neuroendocrinologia</option>
                            <option value="Neurofisiologia">Neurofisiologia</option>
                            <option value="Neurofisiologia Clínica">Neurofisiologia Clínica</option>
                            <option value="Neurologia">Neurologia</option>
                            <option value="Neurologia Clínica">Neurologia Clínica</option>
                            <option value="Neurologia Comportamental">Neurologia Comportamental</option>
                            <option value="Neurologia e Neurocirurgia">Neurologia e Neurocirurgia</option>
                            <option value="Neurologia Pediátrica">Neurologia Pediátrica</option>
                            <option value="Neuropediatria">Neuropediatria</option>
                            <option value="Neurorradiologia">Neurorradiologia</option>
                            <option value="Nutrição">Nutrição</option>
                            <option value="Obstetrícia">Obstetrícia</option>
                            <option value="Odonto Pediatria">Odonto Pediatria</option>
                            <option value="Odontogeriatria">Odontogeriatria</option>
                            <option value="Odontologia">Odontologia</option>
                            <option value="Odontologia  Geral">Odontologia  Geral</option>
                            <option value="Odontologia - Estomatologia">Odontologia - Estomatologia</option>
                            <option value="Odontologia Buco">Odontologia Buco</option>
                            <option value="Odontologia Buco - Dor Face - atm">Odontologia Buco - Dor Face - atm</option>
                            <option value="Odontologia Buco - Implantes">Odontologia Buco - Implantes</option>
                            <option value="Odontologia Buco - Pacientes Especiais - Check Up">Odontologia Buco - Pacientes Especiais - Check Up</option>
                            <option value="Odontologia Buco - Trauma - Check Up">Odontologia Buco - Trauma - Check Up</option>
                            <option value="Odontologia Buco Facial - Prot bmf">Odontologia Buco Facial - Prot bmf</option>
                            <option value="Odontologia Check Up">Odontologia Check Up</option>
                            <option value="Odontologia Dentística">Odontologia Dentística</option>
                            <option value="Odontologia Dentística - Clareamento">Odontologia Dentística - Clareamento</option>
                            <option value="Odontologia Dentística - Prótese">Odontologia Dentística - Prótese</option>
                            <option value="Odontologia Dentística e Endodontia">Odontologia Dentística e Endodontia</option>
                            <option value="Odontologia do Esporte">Odontologia do Esporte</option>
                            <option value="Odontologia Dor Oro-facial">Odontologia Dor Oro-facial</option>
                            <option value="Odontologia Endodontia - Canal">Odontologia Endodontia - Canal</option>
                            <option value="Odontologia Estomatologia">Odontologia Estomatologia</option>
                            <option value="Odontologia Mod. Ortodontia">Odontologia Mod. Ortodontia</option>
                            <option value="Odontologia Ortodontia">Odontologia Ortodontia</option>
                            <option value="Odontologia para Pacientes com Necessidades Especiais">Odontologia para Pacientes com Necessidades Especiais</option>
                            <option value="Odontologia Pediatria - Check Up">Odontologia Pediatria - Check Up</option>
                            <option value="Odontologia Pediatria Pacientes Especiais">Odontologia Pediatria Pacientes Especiais</option>
                            <option value="Odontologia Periodontia - Gengiva">Odontologia Periodontia - Gengiva</option>
                            <option value="Odontologia Prótese Dentária - Implantes">Odontologia Prótese Dentária - Implantes</option>
                            <option value="Odontopediatria">Odontopediatria</option>
                            <option value="Oftalmologia">Oftalmologia</option>
                            <option value="Oncologia">Oncologia</option>
                            <option value="Oncologia - Hematologia">Oncologia - Hematologia</option>
                            <option value="Oncologia - Patologia">Oncologia - Patologia</option>
                            <option value="Oncologia - Radioterapia">Oncologia - Radioterapia</option>
                            <option value="Oncologia Clínica">Oncologia Clínica</option>
                            <option value="Oncologia Pediátrica">Oncologia Pediátrica</option>
                            <option value="Oncologia Pélvica">Oncologia Pélvica</option>
                            <option value="Ortodontia">Ortodontia</option>
                            <option value="Ortodontia e Ortopedia dos Maxilares">Ortodontia e Ortopedia dos Maxilares</option>
                            <option value="Ortodontia e Ortopedia Facial">Ortodontia e Ortopedia Facial</option>
                            <option value="Ortopedia">Ortopedia</option>
                            <option value="Ortopedia - Traumatologia">Ortopedia - Traumatologia</option>
                            <option value="Ortopedia - Traumatologia - Coluna">Ortopedia - Traumatologia - Coluna</option>
                            <option value="Ortopedia - Traumatologia - Joelho">Ortopedia - Traumatologia - Joelho</option>
                            <option value="Ortopedia - Traumatologia - Mão">Ortopedia - Traumatologia - Mão</option>
                            <option value="Ortopedia - Traumatologia - Ombro">Ortopedia - Traumatologia - Ombro</option>
                            <option value="Ortopedia - Traumatologia - Pé">Ortopedia - Traumatologia - Pé</option>
                            <option value="Ortopedia - Traumatologia - Quadril">Ortopedia - Traumatologia - Quadril</option>
                            <option value="Ortopedia e Traumatologia">Ortopedia e Traumatologia</option>
                            <option value="Ortopedia Pediátrica">Ortopedia Pediátrica</option>
                            <option value="Otorrinolaringologia">Otorrinolaringologia</option>
                            <option value="Otorrinolaringologia - Cirurgia Nasal">Otorrinolaringologia - Cirurgia Nasal</option>
                            <option value="Otorrinolaringologia - Laringe">Otorrinolaringologia - Laringe</option>
                            <option value="Otorrinolaringologista">Otorrinolaringologista</option>
                            <option value="Patologia">Patologia</option>
                            <option value="Pediatria">Pediatria</option>
                            <option value="Pediatria - Hebiatria">Pediatria - Hebiatria</option>
                            <option value="Pediatria - Med. Adolescentes">Pediatria - Med. Adolescentes</option>
                            <option value="Pediatria Adolescentes">Pediatria Adolescentes</option>
                            <option value="Periodontia">Periodontia</option>
                            <option value="Pneumologia">Pneumologia</option>
                            <option value="Pneumologia Clínica">Pneumologia Clínica</option>
                            <option value="Pneumologia Pediátrica">Pneumologia Pediátrica</option>
                            <option value="Pneumologista">Pneumologista</option>
                            <option value="Polissonografista">Polissonografista</option>
                            <option value="Pós Transplante Hepático">Pós Transplante Hepático</option>
                            <option value="Pré e Pós Transplante de Medula Óssea">Pré e Pós Transplante de Medula Óssea</option>
                            <option value="Pré Transplante Hepático">Pré Transplante Hepático</option>
                            <option value="Prevenção Psicologia">Prevenção Psicologia</option>
                            <option value="Proctologia">Proctologia</option>
                            <option value="Prótese Dentária">Prótese Dentária</option>
                            <option value="Psicologia">Psicologia</option>
                            <option value="Psiquiatria">Psiquiatria</option>
                            <option value="Psiquiatria da Infância">Psiquiatria da Infância</option>
                            <option value="Radiologia">Radiologia</option>
                            <option value="Radiologia - Ecografia">Radiologia - Ecografia</option>
                            <option value="Radiologia - Ecografia">Radiologia - Ecografia</option>
                            <option value="Radiologia - Mamografia">Radiologia - Mamografia</option>
                            <option value="Radiologia - Tomografia">Radiologia - Tomografia</option>
                            <option value="Radioterapia">Radioterapia</option>
                            <option value="Reconstrução Mamária">Reconstrução Mamária</option>
                            <option value="Reumatologia">Reumatologia</option>
                            <option value="Terapia Intensiva">Terapia Intensiva</option>
                            <option value="Terapia Intensiva Pediátrica">Terapia Intensiva Pediátrica</option>
                            <option value="Transplante de Medula Óssea">Transplante de Medula Óssea</option>
                            <option value="Transplante de Pâncreas">Transplante de Pâncreas</option>
                            <option value="Transplante de Pulmão">Transplante de Pulmão</option>
                            <option value="Transplante de Rim - Pâncreas">Transplante de Rim - Pâncreas</option>
                            <option value="Transplante Hepático">Transplante Hepático</option>
                            <option value="Transplante Renal">Transplante Renal</option>
                            <option value="Transplantes">Transplantes</option>
                            <option value="Trauma">Trauma</option>
                            <option value="Traumatologia">Traumatologia</option>
                            <option value="Tumor de Coluna">Tumor de Coluna</option>
                            <option value="Tumores da Pele">Tumores da Pele</option>
                            <option value="Tumores Ósseos">Tumores Ósseos</option>
                            <option value="Urologia">Urologia</option>
                            <option value="Urologia - Litiase">Urologia - Litiase</option>
                            <option value="Urologista">Urologista</option>
                            <option value="Vascular">Vascular</option>
                            <option value="Videocirurgia">Videocirurgia</option>
                            <option value="Videolaparoscopia">Videolaparoscopia</option>
                        </select>
                    </div>
                </div>
                <div id="bt">
                    <input type="button" value="buscar" id="Enviar" name="Enviar" >                           
                </div>
            </div>
            <div id="info">
                <ul>
                    <li>Agenda Fácil é um portal que tem por objetivo aproximar médicos e pacientes.</li>
                    <li>Não precisa sair de casa para agendar uma consulta, nem aguardar em filas ou ficar esperando para falar com um atendente.</li>
                    <li>Acesso é rádipo e fácil disponivel 24 horas por dia.</li>
                    <li>Consulte uma especialidade e escolha qual melhor dia e horário.</li>
                    <li>São diversas especialidades e médicos, valores são reduzidos e você só paga pela consulta.</li>
                </ul>  
            </div>
        </div>
    </div>

    <div class="columnContainer clearFix">
        <div id="infoContainer" >
            <div id="info1">
                <p style="padding-top: 2px; text-indent: 60px;"> agendar uma consulta é </p>                                
                <p style="text-indent: 60px;"> simples e fácil</p>
                <p style="padding-top: 21px;text-indent:110px">1º escolha uma especialidade</p>
            </div>

            <div id="info2">
                <p style="padding-top: 2px; text-indent: 110px;">2º escolha o horário</p>
                <p style="text-indent: 110px;"> e o médico </p>
                <p style="padding-top: 21px;text-indent:60px">3º agende uma consulta</p>
            </div>

            <div id="info3">
                <p style="text-indent: 60px; padding-top: 11px;">4º efetue o pagamento</p>                            
                <p style="padding-top: 30px;text-indent:110px">5º aguarde a confirmação e pronto!</p>
            </div>
        </div>
    </div>                

</div>