<?php $this->headScript()->setSeparator(PHP_EOL)->prependFile($this->baseUrl('/js/site/index/login.js')); ?>
<div  align="center" class="columnContainer clearFix">
<span class="info">
        <p>para consultas, agendamentos ou alteração de dados cadastrais, </p><p>acesse o painel do usuário com seu email e senha</p>
</span></div>
<div class="columnContainer clearFix">
    <div class="content">       
        <div id="login_cliente_title">login <?php echo $this->erro ?></div>
        <div id="login_cliente" >
        <?php echo $this->form ?>    
        </div>
        <div id="esqueci_minha_senha"><a href="">esqueci minha senha</a> <?php echo $this->erro ?></div>
    </div>    
    

</div>
<div class="columnContainer clearFix"></div> 
