

    <div class="columnContainer clearFix">
        
        <div id="quemsomos">
         
            <div id="info">
                <ul>
                    <li>Somos uma empresa de tecnologia situada em Porto Alegre - Rio Grande Do Sul. </li>
                    <li>Após vários anos de desenvolvimento chegamos a Agenda Fácil.</li>
                    <li>Que atráves da Internet agiliza a marcação sem filas ou longa espera no telefone, além de ser mais econômico.</li>
                    
                </ul>  
            </div>
        </div>
    </div>

              

