<?php $this->headScript()->setSeparator(PHP_EOL)->prependFile($this->baseUrl('/js/site/clinica/cadastro.js')); ?>
<div class="columnContainer clearFix" align="center"><span class="title">Cadastro</span></div>
<div class="columnContainer clearFix"></div>
<div class="columnContainer clearFix">
    <div class="content" align="center">
        <div style="width: 394px;text-align: left;">
        <?php echo $this->form ?>
        </div>    
    </div>
</div>