<?php echo $this->doctype()?> 
<html lang="pt-br">
<head>
	<meta charset="UTF-8">
<?php 
$this->headTitle()->append('Layout e módulos - Zend Framework');
$this->headTitle()->setSeparator(' - ');
echo $this->headTitle(),PHP_EOL;
$this->headMeta()->headMeta ('Matias Rezende', 'author');
				 
$this->headLink()->setSeparator(PHP_EOL)
		 ->prependStylesheet($this->baseUrl('estilos/estilo.css'));

$this->headScript ()->setSeparator(PHP_EOL)
		    ->prependFile ($this->baseUrl('scripts/jquery/jquery-1.6.1.min.js') );

echo $this->headMeta(),PHP_EOL;
echo $this->headLink(),PHP_EOL;
echo $this->headScript();
?> 
</head>
<body>
	<div id="wrapper">
		<div id="content">
			<h1>Modulo Site</h1>
			<?php echo $this->layout()->content;?>
		</div><!-- /content -->
	</div><!-- /wrapper -->
</body>
</html>

