<?php echo $this->doctype()?> 
<html lang="pt-br">
<head>
    
<?php 
    
$this->headTitle()->append('Agenda Fácil');
$this->headTitle()->setSeparator(' - ');
$this->headMeta()->headMeta ('Rossano Bavaresco', 'author');
$this->headLink()->setSeparator(PHP_EOL)->prependStylesheet($this->baseUrl('css/piweb.css'));
//$this->headScript ()->setSeparator(PHP_EOL)->prependFile($this->baseUrl('js/jquery/jquery-1.6.1.min.js') );


echo $this->headTitle(),PHP_EOL;
echo $this->headMeta(),PHP_EOL;
echo $this->headLink(),PHP_EOL;
echo $this->headScript();
?> 

</head>
    <body>        
        <div class="clearFix" id="wrapper">
            <header>
                <nav>                    
                    <div id="pacientes">
                                <div style="width: 250px;" class="title">Para Pacientes</div>                            
                                <div id="arrow"  style="height: 20px;"></div>
                                <div class="item" ><a href="#"><p>Cadastre-se,é gratuíto</p><p>você só paga às consultas.</p></a></div>                                
                                <div id="arrow"></div>
                                <div class="item"><a href="#"><p>Como funciona</p></a></div>
                                <div id="arrow"></div>
                                <div class="item"><a href="#"><p>login</p></a></div>
                        </div>
                    
                        <div id="clinicas">
                               <div style="width: 250px;" class="title">Para Clínicas e Médicos</div>
                               <div id="arrow"></div>
                               <div class="item"><a href="#"><p>Cadastre-se aqui</p></a></div>
                               <div id="arrow"></div>                               
                               <div class="item"><a href="#"><p>Contato</p></a></div>
                        </div>
                </nav>
            </header>
            
            <div id="mainContent">
            <?php   ?>
            </div>
            
            <footer>
                <div id="links" align="center">
                    <div>
                        <span><a href="#1">quem somos</a></span>
                        <span>|</span>
                        <span><a href="#2">como funciona</a></span>
                        <span>|</span>
                        <span><a href="#3">contato</a></span>
                        <span>|</span>
                        <span><a href="#4">cadastro</a></span>
                    </div>                    
                    <span><img src="<?php echo $this->baseUrl('/images/fone.png')  ?>" border="0" ></span>
                    <span>51 3423-8911</span>                   
                </div>
            </footer>            
          </div>        
    </body>
</html>

