<?php $this->headLink()->setSeparator(PHP_EOL)->appendStylesheet($this->baseUrl('/css/clinica/atendimento.css')); ?>
<?php $this->headScript()->setSeparator(PHP_EOL)->prependFile($this->baseUrl('/js/clinica/atendimento.js')); ?>

<div  align="center" class="columnContainer clearFix"><span class="title">Gerenciamento clínico</span></div>
<div class="columnContainer clearFix">
    <div class="content">        
        
        <div id="table">
            <div id="cell">
                <div class="conteudo">
                    
                    <div id="gridlist-medicos" >                        
                        
                        
                        <div style="width: 394px;text-align: left;">
                            <h4 style="text-align: center;">Atendimento Finalizado</h4>
                            <h4 style="text-align: center;"><a href="/clinica/atendimento/atendimento/">verificar novo atendimento</a></h4>
                        </div>
                        
                        
                    </div>
                         
                         
                </div>                
            </div>
        </div>
        
    </div> 
</div>
<div class="columnContainer clearFix"></div> 
