<?php $this->headLink()->setSeparator(PHP_EOL)->appendStylesheet($this->baseUrl('/css/agenda.css')); ?>
<?php $this->headScript()->setSeparator(PHP_EOL)->prependFile($this->baseUrl('/js/clinica/clinica.js')); ?>

<div  align="center" class="columnContainer clearFix"><span class="title">Gerenciamento clínico</span></div>
<div class="columnContainer clearFix"></div>
<div class="columnContainer clearFix">
    <div class="content">
        <div class="grade">
            <div class="data">Agenda para  <?php echo date('d/m/Y') ?> </div>
            <div class="horarios">
                <table border="0" cellpadding="0" cellspacing="5">
            <?php if(isset($this->dados)): ?>       
                    <thead>
                    <tr>
                        <th>horário</th><th>paciente</th> <th>médico</th> <th>especialidade</th> <th>status</th> <th>ação</th>
                    </tr>
                   </thead>
                    <?php foreach ($this->dados as $dado): ?>
                    <tr>
                        <td><?php echo $dado['horario'] ?></td>
                        <td><?php echo $dado['paciente'] ?></td>
                        <td><?php echo $dado['medico'] ?></td>
                        <td><?php echo $dado['especialidade'] ?></td>
                        <td>
                            <?php 
                                switch ($dado['st_atend']){
                                    case 0:
                                        echo 'aguardando';
                                        break;
                                    case 1 :
                                        echo '<p style="color:#00cc66;">atendimento</p>';
                                        break;
                                    case 2:
                                        echo '<p style="color:#000;">finalizado</p>';
                                        break;                                        
                                    default : break;        
                                }
                            ?>
                        </td>
                        <td id="bt-action">
                            <form action="/clinica/agenda/" method="POST" id="atendimento" name="atendimento_<?php echo $dado['id_consulta'] ?>">
                                <input type="hidden" name="id_consulta" value="<?php echo $dado['id_consulta'] ?>">
                                
                                <?php if($dado['st_atend'] == 0 || $dado['st_atend'] == NULL ): ?>
                                    <input type="submit" id="<?php echo $dado['id_consulta'] ?>"  name="button" value="atender">
                                <?php else: ?>
                                    <input type="submit" disabled="disabled" title="em atendimento, para cancelar entre em contato com o médico" id="disabled" name="button" value="disabled">
                                <?php endif; ?>
                                    
                            </form></td>
                    </tr>                    
                    <?php endforeach; ?>
             <?php else: ?> 
                    <tr><td><h4 style="width: 590px; text-align: center;">Nenhum agendamento encontrado para hoje</h4></td></tr>
             <?php endif; ?>              
                </table>
            </div>
            <div class="line"></div>

        </div>        
    </div>
</div> 
