<?php echo $this->doctype()?> 
<html lang="pt-br">
<head>
    
<?php 
    
$this->headTitle()->prepend('Agenda Fácil');
$this->headTitle()->setSeparator(' - ');
$this->headMeta()->headMeta ('Rossano Bavaresco', 'author');
$this->headLink()->setSeparator(PHP_EOL)->prependStylesheet($this->baseUrl('/css/jquery-ui.css'));
$this->headLink()->setSeparator(PHP_EOL)->prependStylesheet($this->baseUrl('/css/piweb.css'));

$this->headScript()->setSeparator(PHP_EOL)->prependFile($this->baseUrl('/js/site.js'));
$this->headScript()->setSeparator(PHP_EOL)->prependFile($this->baseUrl('/js/jquery-ui.js'));
$this->headScript()->setSeparator(PHP_EOL)->prependFile($this->baseUrl('/js/jquery.mask.js'));
$this->headScript()->setSeparator(PHP_EOL)->prependFile($this->baseUrl('/js/jquery-1.11.1.min.js'));


echo $this->headTitle(),PHP_EOL;
echo $this->headMeta(),PHP_EOL;
echo $this->headLink(),PHP_EOL;
echo $this->headScript();
?> 

</head>
    <body>        
        <div class="clearFix" id="wrapper">
            <header>
                <nav>                    
                        <div id="pacientes">
                                <div style="width: 250px;" class="title">&nbsp;</div>
                                
                                <div id="arrow"></div>                                
                                <div class="item"><a href="<?php echo $this->baseUrl('/adm') ?>"><p>listar</p></a></div>
                                
                                <div id="arrow"></div>
                                <div class="item"><a href="<?php echo $this->baseUrl('/adm/index/desativados/') ?>"><p>pendentes de ativação </p></a></div>
                                
                                <div id="arrow"></div>
                                <div class="item"><a href="<?php echo $this->baseUrl('/adm/index/cadastro-medico/') ?>"><p>cadastro de médicos</p></a></div>                                
                                
                                <div id="arrow"></div>
                                <div class="item"><a href="<?php echo $this->baseUrl('/adm/index/editar-medico/') ?>"><p>editar médico</p></a></div>                                                                
                        </div>
                    
                        <div id="clinicas">
                               <div style="width: 250px;" class="title">&nbsp;</div>
                               <div id="arrow"></div>
                               <div class="item"><a href="<?php echo $this->baseUrl('/adm/index/vincular-medico/') ?>"><p>vincular m&eacute;dico</p></a></div>                               
                               
                               <div id="arrow"></div>
                               <div class="item"><a href="<?php echo $this->baseUrl('/adm/index/logout') ?>"><p>logout</p></a></div>
                               
                               <div id="arrow"></div>
                               <div class="item"><a href="<?php echo $this->baseUrl('/') ?>"><p>home</p></a></div>
                        </div>
                </nav>
            </header>
            
            <div id="mainContent">
            <?php echo $this->layout()->content ?>
            </div>
            
            <footer>
                <div id="links" align="center">
                    <div>
                        <span><a href="<?php echo $this->baseUrl('/')  ?>">home</a></span>
                        <span>|</span>                        
                        <span><a href="/site/index/quemsomos/">quem somos</a></span>
                        <span>|</span>
                        <span><a href="/site/index/contato/">contato</a></span>
                        <span>|</span>
                        <span><a href="/site/clinica/cadastro">cadastro</a></span>
                    </div>                    
                    <span><img src="<?php echo $this->baseUrl('/images/fone.png')  ?>" border="0" ></span>
                    <span>51 3423-8911</span>                   
                </div>
            </footer>            
          </div>        
    </body>
</html>

