<?php $this->headLink()->setSeparator(PHP_EOL)->appendStylesheet($this->baseUrl('/css/clinica/horarios.css')); ?>

<div  align="center" class="columnContainer clearFix"><span class="title">Gerenciamento clínico</span></div>
<div class="columnContainer clearFix">
    <div class="content">        
        
        <div id="table">
            <div id="cell">
                Teste
            </div>
        </div>
        
    </div> 
</div>
<div class="columnContainer clearFix"></div> 
