<div  align="center" class="columnContainer clearFix"><span class="title">Gerenciamento clínico</span></div>
<div class="columnContainer clearFix">
    <div class="content">        
        
        <div id="table">
            <div id="cell">
                <div class="conteudo">
                    
                    <div id="gridlist-medicos" >                        
                        
                        <div class="item-list-medico">
                            <div class="nome">Dr Paulo Moreira</div>
                            <div class="bt"><span>vincular</span></div>
                        </div>                       
                        
                    </div>
                         
                         
                </div>                
            </div>
        </div>
        
    </div> 
</div>
<div class="columnContainer clearFix"></div> 
